config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy]
  end
  resources :posts, only: %i[index show] do
    resources :comments, only: %i[new create destroy]
    resources :likes, only: :create
  end

  get 'users/:user_id/posts_list', to: 'api#list_posts', as: :list_posts
  get 'users/:user_id/posts/:post_id/comments_list', to: 'api#list_comments', as: :list_comments
  post 'users/:user_id/posts/:post_id/comment_create', to: 'api#create_comment', as: :create_comment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true

  def recent_three_posts
    posts.last(3)
  end

  after_save :add_token

  def add_token
    update_column(:authentication_token, ApiHelper::JsonWebToken.encode(email))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<section class="user-index-cont">
  <button type="button" class="create-btn">
    <%= link_to "Create A Post For The First User", new_user_post_path(@users.first.id) , class: "link-btn" %>
  </button>
  <% @users.each do |user| %>
  <a href='/users/<%= user.id %>'>
    <%= render 'shared/user', user:user %>
    <a>
    <% end %>
    <%= button_to "logout", destroy_user_session_path, method: :delete  %>
  </section>

app/views/users/show.html.erb
<section>
  <%= render 'shared/user', user:@user %>
  <div class="bio-heading">
    <h4>Bio:</h4>
    <p><%= @user.bio %><p>
  </div>   
  <ul class="list">
    <% if @user.posts.count > 0 %>
    <% @user.recent_three_posts.each do |post| %>
      <a href="/users/<%= @user.id %>/posts/<%= post.id %>" >
        <%= render 'shared/post', post: post %>
      </a>
    <% end %>
  <% else %>
    <li>No Posts</li>
  <% end %>
</ul>
  <div class="btn">
  <a href="/users/<%= @user.id %>/posts"><button type="button">See All Posts</button></a>
  </div>
</section>