config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy]
  end
  resources :posts, only: %i[index show] do
    resources :comments, only: %i[new create destroy]
    resources :likes, only: :create
  end

  get 'users/:user_id/posts_list', to: 'api#list_posts', as: :list_posts
  get 'users/:user_id/posts/:post_id/comments_list', to: 'api#list_comments', as: :list_comments
  post 'users/:user_id/posts/:post_id/comment_create', to: 'api#create_comment', as: :create_comment
end

app/views/shared/_comments.html.erb
<% comments.each do |comment| %>
    <li class='comment'><%= comment.author.name %> : <%= comment.text%></li>
  <% end %>

app/views/shared/_new_comment.html.erb
<%= form_with model: Comment, url: user_post_comments_path(@post.author, @post),class:'comment-form', method: :post do |form| %>
  <div class= "mb-3 col-md-6"><%= form.text_field :text, placeholder: 'Write your comment here...', class:"form-control" %></div>
  <div class = "mb-3"><%= form.submit "Add a comment", class:"btn btn-primary" %></div>
<% end %>

app/views/shared/_new_like.html.erb
  <%= form_with url: user_post_likes_path(@post.author, @post), method: :post do |form| %>
      <div class= "mb-3"><%= form.submit "Like", class:"btn btn-primary" %></div>
      <% end %>

app/views/shared/_post.html.erb
<li>
      <h4><%= post.title %></h4>
      <p><%= post.text.first(150) %>...</p>
      <span>
       Comments: <%= post.comments_counter %> ,
       Likes: <%= post.likes_counter %>
      </span>
</li>

app/views/shared/_user.html.erb
<div class="user-card-shared">
    <div class="user-card-img">
      <img src="<%= user.photo %>" alt="user avatar">
    </div>  
    <div>
      <h2><%= user.name %></h2>
      <h4>Number of posts: <%= user.posts_counter %></h4>
    </div>
</div>

app/views/shared/new_like.html.erb
  <%= form_with url: user_post_likes_path(@post.author, @post), method: :post do |form| %>
        <%= form.submit "Like", class:"submit-btn" %>
      <% end %>