config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy]
  end
  resources :posts, only: %i[index show] do
    resources :comments, only: %i[new create destroy]
    resources :likes, only: :create
  end

  get 'users/:user_id/posts_list', to: 'api#list_posts', as: :list_posts
  get 'users/:user_id/posts/:post_id/comments_list', to: 'api#list_comments', as: :list_comments
  post 'users/:user_id/posts/:post_id/comment_create', to: 'api#create_comment', as: :create_comment
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: 'post_id'
  has_many :likes, foreign_key: 'post_id'

  after_save :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_five_comments
    comments.last(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: params[:user_id])
  end

  def show
    @post = Post.includes(comments: [:author]).find(params[:id])
  end

  # a method to create a new form for a post
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    # respond to block
    respond_to do |format|
      format.html do
        # if save is successful
        if @post.save
          # redirect to index
          redirect_to "/users/#{@post.author.id}/posts/#{@post.id}"
        else

          render :new
        end
      end
    end
  end

  def destroy
    post = Post.find(params[:id])
    user = User.find(post.author_id)
    user.post_counter -= 1
    post.destroy
    user.save
    flash[:success] = 'You have deleted this post!'
    flash[:success] = 'You have deleted this post!'
    redirect_to user_path(current_user.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :likes_counter, :comments_counter)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<section >
  <%= render'shared/user', user: @user %>
    <% @posts.each do |post| %>
  <a <a href="/users/<%= @user.id %>/posts/<%= post.id %>">
    <div class="list-wrapper">
    <ul class="post-list"><%= render 'shared/post', post: post %></ul>
    <ul class="comments-list">
      <% if post.comments_counter > 0 %>
            <%= render 'shared/comments', comments: post.recent_five_comments %>
      <% else %>
        <li>No comments</li>
      <% end %>
      <ul>
    </div>
  <a>
    <% end %>
  <div class="btn"> 
  <button type='button'>Pagination</button>
  </div>

</section>

app/views/posts/new.html.erb
<div class="forms">
  <h1>Create a Post </h1>
  <%= form_with model: Post, url: user_posts_path, class:"post-form", method: :post do |form| %>
      <div class= "mb-3 col-md-6">
      <%= form.hidden_field :comments_counter, value:0 %>
      </div>
      <div class= "mb-3 col-md-6">
      <%= form.hidden_field :likes_counter, value:0 %>
      </div>
      <div  class= "mb-3 col-md-6" >
        <%= form.label :title,"Title", class:'label' %>
        <%= form.text_field :title, placeholder: 'Title of the post', class:"form-control" %>
      </div>
      <div  class= "mb-3 col-md-6">
        <%= form.label :text, "Content", class:'label' %>
        <%= form.text_area :text, placeholder: 'Write your post', class:"form-control" %>
      </div>
      <div  class= "mb-3">
      <%= form.submit "Submit Post", class:"btn btn-primary", id:"post-btn" %>
      </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<section >
<div class="post-wrapper">
<div>
  <span> <%= @post.title %> By  <%= @post.author.name %> </span>
  <span>
    Comments: <%= @post.comments_counter %> , Likes: <%= @post.likes_counter %>
  </span>
</div>
  <p><%= @post.text %></p>
  <div class="post-btns">
  <%= render'shared/new_like', post: @post %>
</div>
  <ul class="comments-list">
      <% if @post.comments_counter > 0 %>
          <%= render '/shared/comments', comments: @post.comments %>
      <% else %>
        <li>No comments</li>
      <% end %> 
  <%= render 'shared/new_comment', post: @post%>
  </ul>   
</section>